### ISSUE TITLE
Is it possible to specify a folder to save archived logs?

### ISSUE THREAD

**Issue by sergejkaravajnij** [peterherrmann/BetterLog#22]
Hi! 
I’ve been using the library for a while and found that archived logs drop to the root of the GDrive. 
So that’s why the question appeared. 
Is it possible to specify a folder to save archived logs?

**Comment by peterherrmann** [comment]
The old log is created by a Spreadsheet.copy. If this does put the copy
into the folder, you would need to do this yourself.

**Comment by sergejkaravajnij** [comment]
> The old log is created by a Spreadsheet.copy. If this does put the copy into the folder, you would need to do this yourself.

Hi, Peter! 
Thanks for your quick answer. 
I see your point. 
So, in order to have requested functional, it’s required to use DriveApp methods which are out of the scope of the library, right?

**Comment by andrewroberts** [comment]
That's right. It would just need a few DriveApp commands in rollLogOver_(). Be aware of the upcoming ["Drive shortcut" issue](https://cloud.google.com/blog/products/g-suite/simplifying-google-drives-folder-structure-and-sharing-models) though and remove it from the root first (orphan it) and then add it to the destination folder otherwise it'll just create a shortcut - maybe??
